apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{.Values.config.redisPassword}}
