apiVersion: v1
kind: Service
metadata:
  name: {{ include "aristo-pem-whatsapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aristo-pem-whatsapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aristo-pem-whatsapp.selectorLabels" . | nindent 4 }}
