apiVersion: v1
kind: Service
metadata:
  name: {{ include "aristo-pem-backend.fullname" . }}-message
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aristo-pem-backend.labels" . | nindent 4 }}
    service: { { include "aristo-pem-backend.fullname" . } }-message
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.grpcServerPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "aristo-pem-backend.selectorLabels" . | nindent 4 }}
    service: { { include "aristo-pem-backend.fullname" . } }-message
