apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aristo-pem-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aristo-pem-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_HOST: {{.Values.config.keycloak.host}}
  KEYCLOAK_ADMIN_USER: {{.Values.config.keycloak.adminUser}}
  KEYCLOAK_ADMIN_PASSWORD: {{.Values.config.keycloak.adminPassword}}
  KEYCLOAK_REALM: {{.Values.config.keycloak.realm}}
  KEYCLOAK_CLIENT_ID: {{.Values.config.keycloak.clientId}}
  KEYCLOAK_ID_OF_CLIENT: {{.Values.config.keycloak.idOfClient}}
  KEYCLOAK_CLIENT_SECRET: {{.Values.config.keycloak.clientSecret}}
  DATABASE_CONNECTION_STRING: {{.Values.config.db.connectionString}}
  DATABASE_NAME: {{.Values.config.db.name}}
  AWS_S3_REGION: {{.Values.config.s3.region}}
  AWS_S3_PUBLIC_BUCKET: {{.Values.config.s3.publicBucket}}
  AWS_S3_PRIVATE_BUCKET: {{.Values.config.s3.privateBucket}}
  AWS_S3_SECRET_KEY: {{.Values.config.s3.secretKey}}
  AWS_S3_ACCESS_KEY: {{.Values.config.s3.accessKey}}

